os: Visual Studio 2022

before_build:
  - nuget restore src\Renci.SshNet.VS2019.sln

build:
  project: src\Renci.SshNet.VS2019.sln
  verbosity: minimal

test_script:
- cmd: >-
    vstest.console /logger:Appveyor src\Renci.SshNet.Tests\bin\Debug\net472\Renci.SshNet.Tests.dll /TestCaseFilter:"TestCategory!=integration&TestCategory!=LongRunning"
    vstest.console /logger:Appveyor src\Renci.SshNet.Tests\bin\Debug\net7.0\Renci.SshNet.Tests.dll /TestCaseFilter:"TestCategory!=integration&TestCategory!=LongRunning"